/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentManagementRouteImport } from './routes/agent-management'
import { Route as AgentPromoCodeRouteImport } from './routes/agent-promo-code'
import { Route as AviatorPredictorRouteImport } from './routes/aviator-predictor'
import { Route as BetRecordsRouteImport } from './routes/bet-records'
import { Route as ControllerRouteImport } from './routes/controller'
import { Route as PersonalInfoRouteImport } from './routes/personal-info'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminPromoBannerRouteImport } from './routes/admin/promo-banner'
import { Route as Games21RouteImport } from './routes/games/21'
import { Route as GamesAviatorRouteImport } from './routes/games/aviator'
import { Route as GamesChickenRoadRouteImport } from './routes/games/chicken-road'
import { Route as GamesCrashRouteImport } from './routes/games/crash'
import { Route as GamesCrazy777RouteImport } from './routes/games/crazy-777'
import { Route as GamesDiceRouteImport } from './routes/games/dice'
import { Route as GamesDragonTigerRouteImport } from './routes/games/dragon-tiger'
import { Route as GamesF1FormulaRouteImport } from './routes/games/f1-formula'
import { Route as GamesGemsMinesRouteImport } from './routes/games/gems-mines'
import { Route as GamesHighOrLowRouteImport } from './routes/games/high-or-low'
import { Route as GamesJackpotRouteImport } from './routes/games/jackpot'
import { Route as GamesKenoRouteImport } from './routes/games/keno'
import { Route as GamesLotteryRouteImport } from './routes/games/lottery'
import { Route as GamesLoveSlotsRouteImport } from './routes/games/love-slots'
import { Route as GamesPlinkoRouteImport } from './routes/games/plinko'
import { Route as GamesRouletteRouteImport } from './routes/games/roulette'
import { Route as GamesSlots777RouteImport } from './routes/games/slots-777'
import { Route as GamesSosRouteImport } from './routes/games/sos'
import { Route as GamesWheelFortuneRouteImport } from './routes/games/wheel-fortune'
import { Route as GamesWingoRouteImport } from './routes/games/wingo'
import { Route as AdminFinanceAdjustmentRouteImport } from './routes/admin/finance/adjustment'
import { Route as AdminFinanceDepositsRouteImport } from './routes/admin/finance/deposits'
import { Route as AdminFinancePaymentSettingsRouteImport } from './routes/admin/finance/payment-settings'
import { Route as AdminFinanceWagerRouteImport } from './routes/admin/finance/wager'
import { Route as AdminFinanceWithdrawalRouteImport } from './routes/admin/finance/withdrawal'
import { Route as AdminGamesAviatorRouteImport } from './routes/admin/games/aviator'
import { Route as AdminGamesWingoRouteImport } from './routes/admin/games/wingo'
import { Route as AdminMembersBettingRouteImport } from './routes/admin/members/betting'
import { Route as AdminMembersFinancialRouteImport } from './routes/admin/members/financial'
import { Route as AdminMembersIpRouteImport } from './routes/admin/members/ip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentManagementRoute = AgentManagementRouteImport.update({
  id: '/agent-management',
  path: '/agent-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPromoCodeRoute = AgentPromoCodeRouteImport.update({
  id: '/agent-promo-code',
  path: '/agent-promo-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorPredictorRoute = AviatorPredictorRouteImport.update({
  id: '/aviator-predictor',
  path: '/aviator-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const BetRecordsRoute = BetRecordsRouteImport.update({
  id: '/bet-records',
  path: '/bet-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllerRoute = ControllerRouteImport.update({
  id: '/controller',
  path: '/controller',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoRoute = PersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoBannerRoute = AdminPromoBannerRouteImport.update({
  id: '/promo-banner',
  path: '/promo-banner',
  getParentRoute: () => AdminRoute,
} as any)
const Games21Route = Games21RouteImport.update({
  id: '/games/21',
  path: '/games/21',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAviatorRoute = GamesAviatorRouteImport.update({
  id: '/games/aviator',
  path: '/games/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesChickenRoadRoute = GamesChickenRoadRouteImport.update({
  id: '/games/chicken-road',
  path: '/games/chicken-road',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrazy777Route = GamesCrazy777RouteImport.update({
  id: '/games/crazy-777',
  path: '/games/crazy-777',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDiceRoute = GamesDiceRouteImport.update({
  id: '/games/dice',
  path: '/games/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDragonTigerRoute = GamesDragonTigerRouteImport.update({
  id: '/games/dragon-tiger',
  path: '/games/dragon-tiger',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesF1FormulaRoute = GamesF1FormulaRouteImport.update({
  id: '/games/f1-formula',
  path: '/games/f1-formula',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGemsMinesRoute = GamesGemsMinesRouteImport.update({
  id: '/games/gems-mines',
  path: '/games/gems-mines',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesHighOrLowRoute = GamesHighOrLowRouteImport.update({
  id: '/games/high-or-low',
  path: '/games/high-or-low',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJackpotRoute = GamesJackpotRouteImport.update({
  id: '/games/jackpot',
  path: '/games/jackpot',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesKenoRoute = GamesKenoRouteImport.update({
  id: '/games/keno',
  path: '/games/keno',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLotteryRoute = GamesLotteryRouteImport.update({
  id: '/games/lottery',
  path: '/games/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLoveSlotsRoute = GamesLoveSlotsRouteImport.update({
  id: '/games/love-slots',
  path: '/games/love-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPlinkoRoute = GamesPlinkoRouteImport.update({
  id: '/games/plinko',
  path: '/games/plinko',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouletteRoute = GamesRouletteRouteImport.update({
  id: '/games/roulette',
  path: '/games/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlots777Route = GamesSlots777RouteImport.update({
  id: '/games/slots-777',
  path: '/games/slots-777',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSosRoute = GamesSosRouteImport.update({
  id: '/games/sos',
  path: '/games/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWheelFortuneRoute = GamesWheelFortuneRouteImport.update({
  id: '/games/wheel-fortune',
  path: '/games/wheel-fortune',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWingoRoute = GamesWingoRouteImport.update({
  id: '/games/wingo',
  path: '/games/wingo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceAdjustmentRoute = AdminFinanceAdjustmentRouteImport.update({
  id: '/finance/adjustment',
  path: '/finance/adjustment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceDepositsRoute = AdminFinanceDepositsRouteImport.update({
  id: '/finance/deposits',
  path: '/finance/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancePaymentSettingsRoute =
  AdminFinancePaymentSettingsRouteImport.update({
    id: '/finance/payment-settings',
    path: '/finance/payment-settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanceWagerRoute = AdminFinanceWagerRouteImport.update({
  id: '/finance/wager',
  path: '/finance/wager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceWithdrawalRoute = AdminFinanceWithdrawalRouteImport.update({
  id: '/finance/withdrawal',
  path: '/finance/withdrawal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesAviatorRoute = AdminGamesAviatorRouteImport.update({
  id: '/games/aviator',
  path: '/games/aviator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesWingoRoute = AdminGamesWingoRouteImport.update({
  id: '/games/wingo',
  path: '/games/wingo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersBettingRoute = AdminMembersBettingRouteImport.update({
  id: '/betting',
  path: '/betting',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AdminMembersFinancialRoute = AdminMembersFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AdminMembersIpRoute = AdminMembersIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => AdminMembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent-management': typeof AgentManagementRoute
  '/agent-promo-code': typeof AgentPromoCodeRoute
  '/aviator-predictor': typeof AviatorPredictorRoute
  '/bet-records': typeof BetRecordsRoute
  '/controller': typeof ControllerRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/promo-banner': typeof AdminPromoBannerRoute
  '/games/21': typeof Games21Route
  '/games/aviator': typeof GamesAviatorRoute
  '/games/chicken-road': typeof GamesChickenRoadRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/crazy-777': typeof GamesCrazy777Route
  '/games/dice': typeof GamesDiceRoute
  '/games/dragon-tiger': typeof GamesDragonTigerRoute
  '/games/f1-formula': typeof GamesF1FormulaRoute
  '/games/gems-mines': typeof GamesGemsMinesRoute
  '/games/high-or-low': typeof GamesHighOrLowRoute
  '/games/jackpot': typeof GamesJackpotRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/lottery': typeof GamesLotteryRoute
  '/games/love-slots': typeof GamesLoveSlotsRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots-777': typeof GamesSlots777Route
  '/games/sos': typeof GamesSosRoute
  '/games/wheel-fortune': typeof GamesWheelFortuneRoute
  '/games/wingo': typeof GamesWingoRoute
  '/admin/finance/adjustment': typeof AdminFinanceAdjustmentRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/payment-settings': typeof AdminFinancePaymentSettingsRoute
  '/admin/finance/wager': typeof AdminFinanceWagerRoute
  '/admin/finance/withdrawal': typeof AdminFinanceWithdrawalRoute
  '/admin/games/aviator': typeof AdminGamesAviatorRoute
  '/admin/games/wingo': typeof AdminGamesWingoRoute
  '/admin/members/betting': typeof AdminMembersBettingRoute
  '/admin/members/financial': typeof AdminMembersFinancialRoute
  '/admin/members/ip': typeof AdminMembersIpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent-management': typeof AgentManagementRoute
  '/agent-promo-code': typeof AgentPromoCodeRoute
  '/aviator-predictor': typeof AviatorPredictorRoute
  '/bet-records': typeof BetRecordsRoute
  '/controller': typeof ControllerRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/promo-banner': typeof AdminPromoBannerRoute
  '/games/21': typeof Games21Route
  '/games/aviator': typeof GamesAviatorRoute
  '/games/chicken-road': typeof GamesChickenRoadRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/crazy-777': typeof GamesCrazy777Route
  '/games/dice': typeof GamesDiceRoute
  '/games/dragon-tiger': typeof GamesDragonTigerRoute
  '/games/f1-formula': typeof GamesF1FormulaRoute
  '/games/gems-mines': typeof GamesGemsMinesRoute
  '/games/high-or-low': typeof GamesHighOrLowRoute
  '/games/jackpot': typeof GamesJackpotRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/lottery': typeof GamesLotteryRoute
  '/games/love-slots': typeof GamesLoveSlotsRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots-777': typeof GamesSlots777Route
  '/games/sos': typeof GamesSosRoute
  '/games/wheel-fortune': typeof GamesWheelFortuneRoute
  '/games/wingo': typeof GamesWingoRoute
  '/admin/finance/adjustment': typeof AdminFinanceAdjustmentRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/payment-settings': typeof AdminFinancePaymentSettingsRoute
  '/admin/finance/wager': typeof AdminFinanceWagerRoute
  '/admin/finance/withdrawal': typeof AdminFinanceWithdrawalRoute
  '/admin/games/aviator': typeof AdminGamesAviatorRoute
  '/admin/games/wingo': typeof AdminGamesWingoRoute
  '/admin/members/betting': typeof AdminMembersBettingRoute
  '/admin/members/financial': typeof AdminMembersFinancialRoute
  '/admin/members/ip': typeof AdminMembersIpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent-management': typeof AgentManagementRoute
  '/agent-promo-code': typeof AgentPromoCodeRoute
  '/aviator-predictor': typeof AviatorPredictorRoute
  '/bet-records': typeof BetRecordsRoute
  '/controller': typeof ControllerRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/promo-banner': typeof AdminPromoBannerRoute
  '/games/21': typeof Games21Route
  '/games/aviator': typeof GamesAviatorRoute
  '/games/chicken-road': typeof GamesChickenRoadRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/crazy-777': typeof GamesCrazy777Route
  '/games/dice': typeof GamesDiceRoute
  '/games/dragon-tiger': typeof GamesDragonTigerRoute
  '/games/f1-formula': typeof GamesF1FormulaRoute
  '/games/gems-mines': typeof GamesGemsMinesRoute
  '/games/high-or-low': typeof GamesHighOrLowRoute
  '/games/jackpot': typeof GamesJackpotRoute
  '/games/keno': typeof GamesKenoRoute
  '/games/lottery': typeof GamesLotteryRoute
  '/games/love-slots': typeof GamesLoveSlotsRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots-777': typeof GamesSlots777Route
  '/games/sos': typeof GamesSosRoute
  '/games/wheel-fortune': typeof GamesWheelFortuneRoute
  '/games/wingo': typeof GamesWingoRoute
  '/admin/finance/adjustment': typeof AdminFinanceAdjustmentRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/payment-settings': typeof AdminFinancePaymentSettingsRoute
  '/admin/finance/wager': typeof AdminFinanceWagerRoute
  '/admin/finance/withdrawal': typeof AdminFinanceWithdrawalRoute
  '/admin/games/aviator': typeof AdminGamesAviatorRoute
  '/admin/games/wingo': typeof AdminGamesWingoRoute
  '/admin/members/betting': typeof AdminMembersBettingRoute
  '/admin/members/financial': typeof AdminMembersFinancialRoute
  '/admin/members/ip': typeof AdminMembersIpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent-management'
    | '/agent-promo-code'
    | '/aviator-predictor'
    | '/bet-records'
    | '/controller'
    | '/personal-info'
    | '/profile'
    | '/promo'
    | '/admin/members'
    | '/admin/promo-banner'
    | '/games/21'
    | '/games/aviator'
    | '/games/chicken-road'
    | '/games/crash'
    | '/games/crazy-777'
    | '/games/dice'
    | '/games/dragon-tiger'
    | '/games/f1-formula'
    | '/games/gems-mines'
    | '/games/high-or-low'
    | '/games/jackpot'
    | '/games/keno'
    | '/games/lottery'
    | '/games/love-slots'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/slots-777'
    | '/games/sos'
    | '/games/wheel-fortune'
    | '/games/wingo'
    | '/admin/finance/adjustment'
    | '/admin/finance/deposits'
    | '/admin/finance/payment-settings'
    | '/admin/finance/wager'
    | '/admin/finance/withdrawal'
    | '/admin/games/aviator'
    | '/admin/games/wingo'
    | '/admin/members/betting'
    | '/admin/members/financial'
    | '/admin/members/ip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent-management'
    | '/agent-promo-code'
    | '/aviator-predictor'
    | '/bet-records'
    | '/controller'
    | '/personal-info'
    | '/profile'
    | '/promo'
    | '/admin/members'
    | '/admin/promo-banner'
    | '/games/21'
    | '/games/aviator'
    | '/games/chicken-road'
    | '/games/crash'
    | '/games/crazy-777'
    | '/games/dice'
    | '/games/dragon-tiger'
    | '/games/f1-formula'
    | '/games/gems-mines'
    | '/games/high-or-low'
    | '/games/jackpot'
    | '/games/keno'
    | '/games/lottery'
    | '/games/love-slots'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/slots-777'
    | '/games/sos'
    | '/games/wheel-fortune'
    | '/games/wingo'
    | '/admin/finance/adjustment'
    | '/admin/finance/deposits'
    | '/admin/finance/payment-settings'
    | '/admin/finance/wager'
    | '/admin/finance/withdrawal'
    | '/admin/games/aviator'
    | '/admin/games/wingo'
    | '/admin/members/betting'
    | '/admin/members/financial'
    | '/admin/members/ip'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent-management'
    | '/agent-promo-code'
    | '/aviator-predictor'
    | '/bet-records'
    | '/controller'
    | '/personal-info'
    | '/profile'
    | '/promo'
    | '/admin/members'
    | '/admin/promo-banner'
    | '/games/21'
    | '/games/aviator'
    | '/games/chicken-road'
    | '/games/crash'
    | '/games/crazy-777'
    | '/games/dice'
    | '/games/dragon-tiger'
    | '/games/f1-formula'
    | '/games/gems-mines'
    | '/games/high-or-low'
    | '/games/jackpot'
    | '/games/keno'
    | '/games/lottery'
    | '/games/love-slots'
    | '/games/plinko'
    | '/games/roulette'
    | '/games/slots-777'
    | '/games/sos'
    | '/games/wheel-fortune'
    | '/games/wingo'
    | '/admin/finance/adjustment'
    | '/admin/finance/deposits'
    | '/admin/finance/payment-settings'
    | '/admin/finance/wager'
    | '/admin/finance/withdrawal'
    | '/admin/games/aviator'
    | '/admin/games/wingo'
    | '/admin/members/betting'
    | '/admin/members/financial'
    | '/admin/members/ip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentManagementRoute: typeof AgentManagementRoute
  AgentPromoCodeRoute: typeof AgentPromoCodeRoute
  AviatorPredictorRoute: typeof AviatorPredictorRoute
  BetRecordsRoute: typeof BetRecordsRoute
  ControllerRoute: typeof ControllerRoute
  PersonalInfoRoute: typeof PersonalInfoRoute
  ProfileRoute: typeof ProfileRoute
  PromoRoute: typeof PromoRoute
  Games21Route: typeof Games21Route
  GamesAviatorRoute: typeof GamesAviatorRoute
  GamesChickenRoadRoute: typeof GamesChickenRoadRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesCrazy777Route: typeof GamesCrazy777Route
  GamesDiceRoute: typeof GamesDiceRoute
  GamesDragonTigerRoute: typeof GamesDragonTigerRoute
  GamesF1FormulaRoute: typeof GamesF1FormulaRoute
  GamesGemsMinesRoute: typeof GamesGemsMinesRoute
  GamesHighOrLowRoute: typeof GamesHighOrLowRoute
  GamesJackpotRoute: typeof GamesJackpotRoute
  GamesKenoRoute: typeof GamesKenoRoute
  GamesLotteryRoute: typeof GamesLotteryRoute
  GamesLoveSlotsRoute: typeof GamesLoveSlotsRoute
  GamesPlinkoRoute: typeof GamesPlinkoRoute
  GamesRouletteRoute: typeof GamesRouletteRoute
  GamesSlots777Route: typeof GamesSlots777Route
  GamesSosRoute: typeof GamesSosRoute
  GamesWheelFortuneRoute: typeof GamesWheelFortuneRoute
  GamesWingoRoute: typeof GamesWingoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-management': {
      id: '/agent-management'
      path: '/agent-management'
      fullPath: '/agent-management'
      preLoaderRoute: typeof AgentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-promo-code': {
      id: '/agent-promo-code'
      path: '/agent-promo-code'
      fullPath: '/agent-promo-code'
      preLoaderRoute: typeof AgentPromoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator-predictor': {
      id: '/aviator-predictor'
      path: '/aviator-predictor'
      fullPath: '/aviator-predictor'
      preLoaderRoute: typeof AviatorPredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-records': {
      id: '/bet-records'
      path: '/bet-records'
      fullPath: '/bet-records'
      preLoaderRoute: typeof BetRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controller': {
      id: '/controller'
      path: '/controller'
      fullPath: '/controller'
      preLoaderRoute: typeof ControllerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info': {
      id: '/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof PersonalInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo-banner': {
      id: '/admin/promo-banner'
      path: '/promo-banner'
      fullPath: '/admin/promo-banner'
      preLoaderRoute: typeof AdminPromoBannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/21': {
      id: '/games/21'
      path: '/games/21'
      fullPath: '/games/21'
      preLoaderRoute: typeof Games21RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/aviator': {
      id: '/games/aviator'
      path: '/games/aviator'
      fullPath: '/games/aviator'
      preLoaderRoute: typeof GamesAviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/chicken-road': {
      id: '/games/chicken-road'
      path: '/games/chicken-road'
      fullPath: '/games/chicken-road'
      preLoaderRoute: typeof GamesChickenRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crazy-777': {
      id: '/games/crazy-777'
      path: '/games/crazy-777'
      fullPath: '/games/crazy-777'
      preLoaderRoute: typeof GamesCrazy777RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/dice': {
      id: '/games/dice'
      path: '/games/dice'
      fullPath: '/games/dice'
      preLoaderRoute: typeof GamesDiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/dragon-tiger': {
      id: '/games/dragon-tiger'
      path: '/games/dragon-tiger'
      fullPath: '/games/dragon-tiger'
      preLoaderRoute: typeof GamesDragonTigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/f1-formula': {
      id: '/games/f1-formula'
      path: '/games/f1-formula'
      fullPath: '/games/f1-formula'
      preLoaderRoute: typeof GamesF1FormulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/gems-mines': {
      id: '/games/gems-mines'
      path: '/games/gems-mines'
      fullPath: '/games/gems-mines'
      preLoaderRoute: typeof GamesGemsMinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/high-or-low': {
      id: '/games/high-or-low'
      path: '/games/high-or-low'
      fullPath: '/games/high-or-low'
      preLoaderRoute: typeof GamesHighOrLowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/jackpot': {
      id: '/games/jackpot'
      path: '/games/jackpot'
      fullPath: '/games/jackpot'
      preLoaderRoute: typeof GamesJackpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/keno': {
      id: '/games/keno'
      path: '/games/keno'
      fullPath: '/games/keno'
      preLoaderRoute: typeof GamesKenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/lottery': {
      id: '/games/lottery'
      path: '/games/lottery'
      fullPath: '/games/lottery'
      preLoaderRoute: typeof GamesLotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/love-slots': {
      id: '/games/love-slots'
      path: '/games/love-slots'
      fullPath: '/games/love-slots'
      preLoaderRoute: typeof GamesLoveSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/plinko': {
      id: '/games/plinko'
      path: '/games/plinko'
      fullPath: '/games/plinko'
      preLoaderRoute: typeof GamesPlinkoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/roulette': {
      id: '/games/roulette'
      path: '/games/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/slots-777': {
      id: '/games/slots-777'
      path: '/games/slots-777'
      fullPath: '/games/slots-777'
      preLoaderRoute: typeof GamesSlots777RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sos': {
      id: '/games/sos'
      path: '/games/sos'
      fullPath: '/games/sos'
      preLoaderRoute: typeof GamesSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/wheel-fortune': {
      id: '/games/wheel-fortune'
      path: '/games/wheel-fortune'
      fullPath: '/games/wheel-fortune'
      preLoaderRoute: typeof GamesWheelFortuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/wingo': {
      id: '/games/wingo'
      path: '/games/wingo'
      fullPath: '/games/wingo'
      preLoaderRoute: typeof GamesWingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance/adjustment': {
      id: '/admin/finance/adjustment'
      path: '/finance/adjustment'
      fullPath: '/admin/finance/adjustment'
      preLoaderRoute: typeof AdminFinanceAdjustmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/deposits': {
      id: '/admin/finance/deposits'
      path: '/finance/deposits'
      fullPath: '/admin/finance/deposits'
      preLoaderRoute: typeof AdminFinanceDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payment-settings': {
      id: '/admin/finance/payment-settings'
      path: '/finance/payment-settings'
      fullPath: '/admin/finance/payment-settings'
      preLoaderRoute: typeof AdminFinancePaymentSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/wager': {
      id: '/admin/finance/wager'
      path: '/finance/wager'
      fullPath: '/admin/finance/wager'
      preLoaderRoute: typeof AdminFinanceWagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/withdrawal': {
      id: '/admin/finance/withdrawal'
      path: '/finance/withdrawal'
      fullPath: '/admin/finance/withdrawal'
      preLoaderRoute: typeof AdminFinanceWithdrawalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games/aviator': {
      id: '/admin/games/aviator'
      path: '/games/aviator'
      fullPath: '/admin/games/aviator'
      preLoaderRoute: typeof AdminGamesAviatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games/wingo': {
      id: '/admin/games/wingo'
      path: '/games/wingo'
      fullPath: '/admin/games/wingo'
      preLoaderRoute: typeof AdminGamesWingoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members/betting': {
      id: '/admin/members/betting'
      path: '/betting'
      fullPath: '/admin/members/betting'
      preLoaderRoute: typeof AdminMembersBettingRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/admin/members/financial': {
      id: '/admin/members/financial'
      path: '/financial'
      fullPath: '/admin/members/financial'
      preLoaderRoute: typeof AdminMembersFinancialRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/admin/members/ip': {
      id: '/admin/members/ip'
      path: '/ip'
      fullPath: '/admin/members/ip'
      preLoaderRoute: typeof AdminMembersIpRouteImport
      parentRoute: typeof AdminMembersRoute
    }
  }
}

interface AdminMembersRouteChildren {
  AdminMembersBettingRoute: typeof AdminMembersBettingRoute
  AdminMembersFinancialRoute: typeof AdminMembersFinancialRoute
  AdminMembersIpRoute: typeof AdminMembersIpRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersBettingRoute: AdminMembersBettingRoute,
  AdminMembersFinancialRoute: AdminMembersFinancialRoute,
  AdminMembersIpRoute: AdminMembersIpRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminPromoBannerRoute: typeof AdminPromoBannerRoute
  AdminFinanceAdjustmentRoute: typeof AdminFinanceAdjustmentRoute
  AdminFinanceDepositsRoute: typeof AdminFinanceDepositsRoute
  AdminFinancePaymentSettingsRoute: typeof AdminFinancePaymentSettingsRoute
  AdminFinanceWagerRoute: typeof AdminFinanceWagerRoute
  AdminFinanceWithdrawalRoute: typeof AdminFinanceWithdrawalRoute
  AdminGamesAviatorRoute: typeof AdminGamesAviatorRoute
  AdminGamesWingoRoute: typeof AdminGamesWingoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminPromoBannerRoute: AdminPromoBannerRoute,
  AdminFinanceAdjustmentRoute: AdminFinanceAdjustmentRoute,
  AdminFinanceDepositsRoute: AdminFinanceDepositsRoute,
  AdminFinancePaymentSettingsRoute: AdminFinancePaymentSettingsRoute,
  AdminFinanceWagerRoute: AdminFinanceWagerRoute,
  AdminFinanceWithdrawalRoute: AdminFinanceWithdrawalRoute,
  AdminGamesAviatorRoute: AdminGamesAviatorRoute,
  AdminGamesWingoRoute: AdminGamesWingoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentManagementRoute: AgentManagementRoute,
  AgentPromoCodeRoute: AgentPromoCodeRoute,
  AviatorPredictorRoute: AviatorPredictorRoute,
  BetRecordsRoute: BetRecordsRoute,
  ControllerRoute: ControllerRoute,
  PersonalInfoRoute: PersonalInfoRoute,
  ProfileRoute: ProfileRoute,
  PromoRoute: PromoRoute,
  Games21Route: Games21Route,
  GamesAviatorRoute: GamesAviatorRoute,
  GamesChickenRoadRoute: GamesChickenRoadRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesCrazy777Route: GamesCrazy777Route,
  GamesDiceRoute: GamesDiceRoute,
  GamesDragonTigerRoute: GamesDragonTigerRoute,
  GamesF1FormulaRoute: GamesF1FormulaRoute,
  GamesGemsMinesRoute: GamesGemsMinesRoute,
  GamesHighOrLowRoute: GamesHighOrLowRoute,
  GamesJackpotRoute: GamesJackpotRoute,
  GamesKenoRoute: GamesKenoRoute,
  GamesLotteryRoute: GamesLotteryRoute,
  GamesLoveSlotsRoute: GamesLoveSlotsRoute,
  GamesPlinkoRoute: GamesPlinkoRoute,
  GamesRouletteRoute: GamesRouletteRoute,
  GamesSlots777Route: GamesSlots777Route,
  GamesSosRoute: GamesSosRoute,
  GamesWheelFortuneRoute: GamesWheelFortuneRoute,
  GamesWingoRoute: GamesWingoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
